### ISSUE TITLE
How to create db tables?

### ISSUE THREAD

**Issue by mariusa** [Michael-Gibbons/OSB#81]
Hi & thanks for the template!

I think I've followed all the steps properly.

The app starts fine but then gives `The table `public.Shop` does not exist in the current database.`

How should the db tables be created? After initial creation, can I just continue adding custom columns to existing tables?

Thanks!

**Comment by mariusa** [comment]
To clarify, `npm run osb init` did ask about the db name, but no password, and left the `.env` `DATABASE_URL` wrong, with `admin:postgres` default user & passwd.

**Comment by Michael-Gibbons** [comment]
@mariusa Extra tables should be defined in your prisma schema 
https://www.prisma.io/docs

As for the user/password in the .env file, I believe you are correct, I did not add anything to dynamically inject that information. I will look into that thank you.

In the meantime you should be able to add in that info yourself, all that env generation code does is save you the trouble of populating the env file yourself.

**Comment by Michael-Gibbons** [comment]
@mariusa This is turning out to be a bug introduced by me in the last update, good catch thank you. Will fix

**Comment by Michael-Gibbons** [comment]
Okay should be fixed, I added prompts for the postgres credentials and added the init command to the dev flow so its abstracted away.

**Comment by mariusa** [comment]
Thanks!
