### ISSUE TITLE
 Shopify announced the deprecation of its GraphQL API in favor of the JSON:API specification  ?

### ISSUE THREAD

**Issue by mariusa** [Michael-Gibbons/OSB#83]
Found this in docs: `Shopify announced the deprecation of its GraphQL API in favor of the [JSON:API specification](https://jsonapi.org/).`

but I can't find any news about this. I'm not sure if it's a joke?

**Comment by Michael-Gibbons** [comment]
https://github.com/Shopify/shopify-app-template-node/issues/1125

**Comment by mariusa** [comment]
Thank you for the (good) news!
